# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arithmatic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arithmatic.proto',
  package='Arithmatic',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x61rithmatic.proto\x12\nArithmatic\"^\n\x0b\x43\x61lculation\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x05\x12\x10\n\x08operator\x18\x03 \x01(\t\x12\t\n\x01\x61\x18\x04 \x01(\x02\x12\t\n\x01\x62\x18\x05 \x01(\x02\x12\x0b\n\x03\x61ns\x18\x06 \x01(\x02\",\n\x03One\x12%\n\x04\x63\x61lc\x18\x01 \x03(\x0b\x32\x17.Arithmatic.Calculationb\x06proto3')
)




_CALCULATION = _descriptor.Descriptor(
  name='Calculation',
  full_name='Arithmatic.Calculation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='Arithmatic.Calculation.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='line', full_name='Arithmatic.Calculation.line', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operator', full_name='Arithmatic.Calculation.operator', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='a', full_name='Arithmatic.Calculation.a', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='Arithmatic.Calculation.b', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ans', full_name='Arithmatic.Calculation.ans', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=126,
)


_ONE = _descriptor.Descriptor(
  name='One',
  full_name='Arithmatic.One',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='calc', full_name='Arithmatic.One.calc', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=172,
)

_ONE.fields_by_name['calc'].message_type = _CALCULATION
DESCRIPTOR.message_types_by_name['Calculation'] = _CALCULATION
DESCRIPTOR.message_types_by_name['One'] = _ONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Calculation = _reflection.GeneratedProtocolMessageType('Calculation', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATION,
  __module__ = 'arithmatic_pb2'
  # @@protoc_insertion_point(class_scope:Arithmatic.Calculation)
  ))
_sym_db.RegisterMessage(Calculation)

One = _reflection.GeneratedProtocolMessageType('One', (_message.Message,), dict(
  DESCRIPTOR = _ONE,
  __module__ = 'arithmatic_pb2'
  # @@protoc_insertion_point(class_scope:Arithmatic.One)
  ))
_sym_db.RegisterMessage(One)


# @@protoc_insertion_point(module_scope)
