// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arithmatic.proto

#include "arithmatic.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_arithmatic_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_arithmatic_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Calculation;
}  // namespace protobuf_arithmatic_2eproto
namespace Arithmatic {
class CalculationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Calculation>
      _instance;
} _Calculation_default_instance_;
class OneDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<One>
      _instance;
} _One_default_instance_;
}  // namespace Arithmatic
namespace protobuf_arithmatic_2eproto {
static void InitDefaultsCalculation() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arithmatic::_Calculation_default_instance_;
    new (ptr) ::Arithmatic::Calculation();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Arithmatic::Calculation::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Calculation =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCalculation}, {}};

static void InitDefaultsOne() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arithmatic::_One_default_instance_;
    new (ptr) ::Arithmatic::One();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Arithmatic::One::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_One =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsOne}, {
      &protobuf_arithmatic_2eproto::scc_info_Calculation.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Calculation.base);
  ::google::protobuf::internal::InitSCC(&scc_info_One.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, file_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, line_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, operator__),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, a_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, b_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::Calculation, ans_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::One, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmatic::One, calc_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Arithmatic::Calculation)},
  { 11, -1, sizeof(::Arithmatic::One)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Arithmatic::_Calculation_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Arithmatic::_One_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "arithmatic.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020arithmatic.proto\022\nArithmatic\"^\n\013Calcul"
      "ation\022\014\n\004file\030\001 \001(\t\022\014\n\004line\030\002 \001(\005\022\020\n\010ope"
      "rator\030\003 \001(\t\022\t\n\001a\030\004 \001(\002\022\t\n\001b\030\005 \001(\002\022\013\n\003ans"
      "\030\006 \001(\002\",\n\003One\022%\n\004calc\030\001 \003(\0132\027.Arithmatic"
      ".Calculationb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 180);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "arithmatic.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_arithmatic_2eproto
namespace Arithmatic {

// ===================================================================

void Calculation::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Calculation::kFileFieldNumber;
const int Calculation::kLineFieldNumber;
const int Calculation::kOperatorFieldNumber;
const int Calculation::kAFieldNumber;
const int Calculation::kBFieldNumber;
const int Calculation::kAnsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Calculation::Calculation()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_arithmatic_2eproto::scc_info_Calculation.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Arithmatic.Calculation)
}
Calculation::Calculation(const Calculation& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.file().size() > 0) {
    file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_);
  }
  operator__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operator_().size() > 0) {
    operator__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operator__);
  }
  ::memcpy(&line_, &from.line_,
    static_cast<size_t>(reinterpret_cast<char*>(&ans_) -
    reinterpret_cast<char*>(&line_)) + sizeof(ans_));
  // @@protoc_insertion_point(copy_constructor:Arithmatic.Calculation)
}

void Calculation::SharedCtor() {
  file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operator__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&line_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ans_) -
      reinterpret_cast<char*>(&line_)) + sizeof(ans_));
}

Calculation::~Calculation() {
  // @@protoc_insertion_point(destructor:Arithmatic.Calculation)
  SharedDtor();
}

void Calculation::SharedDtor() {
  file_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operator__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Calculation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Calculation::descriptor() {
  ::protobuf_arithmatic_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmatic_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Calculation& Calculation::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_arithmatic_2eproto::scc_info_Calculation.base);
  return *internal_default_instance();
}


void Calculation::Clear() {
// @@protoc_insertion_point(message_clear_start:Arithmatic.Calculation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operator__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&line_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ans_) -
      reinterpret_cast<char*>(&line_)) + sizeof(ans_));
  _internal_metadata_.Clear();
}

bool Calculation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Arithmatic.Calculation)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string file = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->file().data(), static_cast<int>(this->file().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Arithmatic.Calculation.file"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 line = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &line_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operator = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operator_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operator_().data(), static_cast<int>(this->operator_().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Arithmatic.Calculation.operator"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float a = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &a_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float b = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &b_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ans = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ans_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Arithmatic.Calculation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Arithmatic.Calculation)
  return false;
#undef DO_
}

void Calculation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Arithmatic.Calculation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string file = 1;
  if (this->file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file().data(), static_cast<int>(this->file().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Arithmatic.Calculation.file");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->file(), output);
  }

  // int32 line = 2;
  if (this->line() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->line(), output);
  }

  // string operator = 3;
  if (this->operator_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operator_().data(), static_cast<int>(this->operator_().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Arithmatic.Calculation.operator");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->operator_(), output);
  }

  // float a = 4;
  if (this->a() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->a(), output);
  }

  // float b = 5;
  if (this->b() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->b(), output);
  }

  // float ans = 6;
  if (this->ans() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->ans(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Arithmatic.Calculation)
}

::google::protobuf::uint8* Calculation::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Arithmatic.Calculation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string file = 1;
  if (this->file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file().data(), static_cast<int>(this->file().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Arithmatic.Calculation.file");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->file(), target);
  }

  // int32 line = 2;
  if (this->line() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->line(), target);
  }

  // string operator = 3;
  if (this->operator_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operator_().data(), static_cast<int>(this->operator_().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Arithmatic.Calculation.operator");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->operator_(), target);
  }

  // float a = 4;
  if (this->a() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->a(), target);
  }

  // float b = 5;
  if (this->b() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->b(), target);
  }

  // float ans = 6;
  if (this->ans() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->ans(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arithmatic.Calculation)
  return target;
}

size_t Calculation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arithmatic.Calculation)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string file = 1;
  if (this->file().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file());
  }

  // string operator = 3;
  if (this->operator_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operator_());
  }

  // int32 line = 2;
  if (this->line() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->line());
  }

  // float a = 4;
  if (this->a() != 0) {
    total_size += 1 + 4;
  }

  // float b = 5;
  if (this->b() != 0) {
    total_size += 1 + 4;
  }

  // float ans = 6;
  if (this->ans() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Calculation::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arithmatic.Calculation)
  GOOGLE_DCHECK_NE(&from, this);
  const Calculation* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Calculation>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arithmatic.Calculation)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arithmatic.Calculation)
    MergeFrom(*source);
  }
}

void Calculation::MergeFrom(const Calculation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arithmatic.Calculation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.file().size() > 0) {

    file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_);
  }
  if (from.operator_().size() > 0) {

    operator__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operator__);
  }
  if (from.line() != 0) {
    set_line(from.line());
  }
  if (from.a() != 0) {
    set_a(from.a());
  }
  if (from.b() != 0) {
    set_b(from.b());
  }
  if (from.ans() != 0) {
    set_ans(from.ans());
  }
}

void Calculation::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arithmatic.Calculation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Calculation::CopyFrom(const Calculation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arithmatic.Calculation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Calculation::IsInitialized() const {
  return true;
}

void Calculation::Swap(Calculation* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Calculation::InternalSwap(Calculation* other) {
  using std::swap;
  file_.Swap(&other->file_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  operator__.Swap(&other->operator__, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(line_, other->line_);
  swap(a_, other->a_);
  swap(b_, other->b_);
  swap(ans_, other->ans_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Calculation::GetMetadata() const {
  protobuf_arithmatic_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmatic_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void One::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int One::kCalcFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

One::One()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_arithmatic_2eproto::scc_info_One.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Arithmatic.One)
}
One::One(const One& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      calc_(from.calc_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Arithmatic.One)
}

void One::SharedCtor() {
}

One::~One() {
  // @@protoc_insertion_point(destructor:Arithmatic.One)
  SharedDtor();
}

void One::SharedDtor() {
}

void One::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* One::descriptor() {
  ::protobuf_arithmatic_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmatic_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const One& One::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_arithmatic_2eproto::scc_info_One.base);
  return *internal_default_instance();
}


void One::Clear() {
// @@protoc_insertion_point(message_clear_start:Arithmatic.One)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  calc_.Clear();
  _internal_metadata_.Clear();
}

bool One::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Arithmatic.One)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Arithmatic.Calculation calc = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_calc()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Arithmatic.One)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Arithmatic.One)
  return false;
#undef DO_
}

void One::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Arithmatic.One)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Arithmatic.Calculation calc = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->calc_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->calc(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Arithmatic.One)
}

::google::protobuf::uint8* One::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Arithmatic.One)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Arithmatic.Calculation calc = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->calc_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->calc(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arithmatic.One)
  return target;
}

size_t One::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arithmatic.One)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Arithmatic.Calculation calc = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->calc_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->calc(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void One::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arithmatic.One)
  GOOGLE_DCHECK_NE(&from, this);
  const One* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const One>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arithmatic.One)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arithmatic.One)
    MergeFrom(*source);
  }
}

void One::MergeFrom(const One& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arithmatic.One)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  calc_.MergeFrom(from.calc_);
}

void One::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arithmatic.One)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void One::CopyFrom(const One& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arithmatic.One)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool One::IsInitialized() const {
  return true;
}

void One::Swap(One* other) {
  if (other == this) return;
  InternalSwap(other);
}
void One::InternalSwap(One* other) {
  using std::swap;
  CastToBase(&calc_)->InternalSwap(CastToBase(&other->calc_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata One::GetMetadata() const {
  protobuf_arithmatic_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmatic_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Arithmatic
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Arithmatic::Calculation* Arena::CreateMaybeMessage< ::Arithmatic::Calculation >(Arena* arena) {
  return Arena::CreateInternal< ::Arithmatic::Calculation >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Arithmatic::One* Arena::CreateMaybeMessage< ::Arithmatic::One >(Arena* arena) {
  return Arena::CreateInternal< ::Arithmatic::One >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
