# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cnn_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cnn_params.proto',
  package='CnnProto',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63nn_params.proto\x12\x08\x43nnProto\"\x17\n\x06Weight\x12\r\n\x01w\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x15\n\x04\x42ias\x12\r\n\x01\x62\x18\x01 \x03(\x02\x42\x02\x10\x01\"K\n\x06Params\x12!\n\x07weights\x18\x01 \x03(\x0b\x32\x10.CnnProto.Weight\x12\x1e\n\x06\x62iases\x18\x02 \x03(\x0b\x32\x0e.CnnProto.Biasb\x06proto3')
)




_WEIGHT = _descriptor.Descriptor(
  name='Weight',
  full_name='CnnProto.Weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='CnnProto.Weight.w', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=53,
)


_BIAS = _descriptor.Descriptor(
  name='Bias',
  full_name='CnnProto.Bias',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='CnnProto.Bias.b', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=76,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='CnnProto.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='CnnProto.Params.weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biases', full_name='CnnProto.Params.biases', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=153,
)

_PARAMS.fields_by_name['weights'].message_type = _WEIGHT
_PARAMS.fields_by_name['biases'].message_type = _BIAS
DESCRIPTOR.message_types_by_name['Weight'] = _WEIGHT
DESCRIPTOR.message_types_by_name['Bias'] = _BIAS
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Weight = _reflection.GeneratedProtocolMessageType('Weight', (_message.Message,), dict(
  DESCRIPTOR = _WEIGHT,
  __module__ = 'cnn_params_pb2'
  # @@protoc_insertion_point(class_scope:CnnProto.Weight)
  ))
_sym_db.RegisterMessage(Weight)

Bias = _reflection.GeneratedProtocolMessageType('Bias', (_message.Message,), dict(
  DESCRIPTOR = _BIAS,
  __module__ = 'cnn_params_pb2'
  # @@protoc_insertion_point(class_scope:CnnProto.Bias)
  ))
_sym_db.RegisterMessage(Bias)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'cnn_params_pb2'
  # @@protoc_insertion_point(class_scope:CnnProto.Params)
  ))
_sym_db.RegisterMessage(Params)


_WEIGHT.fields_by_name['w'].has_options = True
_WEIGHT.fields_by_name['w']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_BIAS.fields_by_name['b'].has_options = True
_BIAS.fields_by_name['b']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
