# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='genom.proto',
  package='Gene',
  syntax='proto3',
  serialized_pb=_b('\n\x0bgenom.proto\x12\x04Gene\",\n\x04Gene\x12\x10\n\x04gene\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x12\n\nevaluation\x18\x02 \x01(\x02\"$\n\x06Genoms\x12\x1a\n\x06genoms\x18\x01 \x03(\x0b\x32\n.Gene.Geneb\x06proto3')
)




_GENE = _descriptor.Descriptor(
  name='Gene',
  full_name='Gene.Gene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gene', full_name='Gene.Gene.gene', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='evaluation', full_name='Gene.Gene.evaluation', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=65,
)


_GENOMS = _descriptor.Descriptor(
  name='Genoms',
  full_name='Gene.Genoms',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genoms', full_name='Gene.Genoms.genoms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=103,
)

_GENOMS.fields_by_name['genoms'].message_type = _GENE
DESCRIPTOR.message_types_by_name['Gene'] = _GENE
DESCRIPTOR.message_types_by_name['Genoms'] = _GENOMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gene = _reflection.GeneratedProtocolMessageType('Gene', (_message.Message,), dict(
  DESCRIPTOR = _GENE,
  __module__ = 'genom_pb2'
  # @@protoc_insertion_point(class_scope:Gene.Gene)
  ))
_sym_db.RegisterMessage(Gene)

Genoms = _reflection.GeneratedProtocolMessageType('Genoms', (_message.Message,), dict(
  DESCRIPTOR = _GENOMS,
  __module__ = 'genom_pb2'
  # @@protoc_insertion_point(class_scope:Gene.Genoms)
  ))
_sym_db.RegisterMessage(Genoms)


_GENE.fields_by_name['gene'].has_options = True
_GENE.fields_by_name['gene']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
